name = "VariationalOnlineStats"
uuid = "19baa3cf-15a9-54b0-b671-5d0d7003ae5b"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.0.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
